version: '3.8'

services:
  springboot-app:
    build: .
    container_name: student-login-app
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/student_database?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: abhayraj
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SERVER_PORT: 8181
